name: 'cas authenticate asset'
description: 'Uses the cas CLI to authenticate digital assets'
branding:
  icon: 'lock'
  color: 'green'
inputs:
  asset:
    description: 'Asset to authenticate'
    required: true
  signerID:
    description: 'The signerID used when notarizing, needed to authenticate the asset'
    required: true
runs:
  using: 'docker'
  image: 'docker://codenotary/cas:latest'
  args:
    - a
    - ${{ inputs.asset }}
    - --signerID=${{ inputs.signerID }}
    - --host=cas.codenotary.com
